apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifts-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shifts
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: shifts
    spec:
      containers:
        - name: shifts
          image: your-docker-image-here
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              value: your-postgres-username
            - name: PGDATABASE
              value: your-postgres-db-name
            - name: PGPASSWORD
              value: your-postgres-password
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: shift-service
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort

