apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: your-docker-image-here
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 80
          env:
            - name: MONGO_DB_HOST
              value: mongo-db
            - name: MONGO_DB_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              value: "users-db"
---
# service-users.yaml
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort             
